# coding=utf-8
# *** WARNING: this file was generated by pulumi-gen-vpc. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "assign_generated_ipv6_cidr_block": "assignGeneratedIpv6CidrBlock",
    "cidr_block": "cidrBlock",
    "enable_classiclink": "enableClassiclink",
    "enable_classiclink_dns_support": "enableClassiclinkDnsSupport",
    "enable_dns_hostnames": "enableDnsHostnames",
    "enable_dns_support": "enableDnsSupport",
    "instance_tenancy": "instanceTenancy",
    "vpc_id": "vpcId",
    "vpc_resource": "vpcResource",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "assignGeneratedIpv6CidrBlock": "assign_generated_ipv6_cidr_block",
    "cidrBlock": "cidr_block",
    "enableClassiclink": "enable_classiclink",
    "enableClassiclinkDnsSupport": "enable_classiclink_dns_support",
    "enableDnsHostnames": "enable_dns_hostnames",
    "enableDnsSupport": "enable_dns_support",
    "instanceTenancy": "instance_tenancy",
    "vpcId": "vpc_id",
    "vpcResource": "vpc_resource",
}
